version: '3.8'
services:
  app:
    image: husseinsaad1/natours:latest
    ports:
      - '3000:3000'
    env_file:
      - ./docker.env
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
    ports:
      - '27018:27017'

networks:
  default:
    driver: bridge

volumes:
  mongo-data:
